var wordList = [
	'account','addition','adjustment','advertisement','agreement','amount',
	'amusement','animal','answer','apparatus','approval','argument','attack',
	'attempt','attention','attraction','authority','balance','behavior',
	'belief','birth','blood','brass','bread','breath','brother','building',
	'burst','business','butter','canvas','cause','chalk','chance','change',
	'cloth','color','comfort','committee','company','comparison','competition',
	'condition','connection','control','copper','cotton','cough','country',
	'cover','crack','credit','crime','crush','current','curve','damage',
	'danger','daughter','death','decision','degree','design','desire',
	'destruction','detail','development','digestion','direction','discovery',
	'discussion','disease','disgust','distance','distribution','division',
	'doubt','drink','driving','education','effect','error','event','example',
	'exchange','existence','expansion','experience','expert','family','father',
	'feeling','fiction','field','fight','flame','flight','flower','force',
	'friend','front','fruit','glass','government','grain','grass','group',
	'growth','guide','harbor','harmony','hearing','history','humor','impulse',
	'increase','industry','insect','instrument','insurance','interest',
	'invention','jelly','journey','judge','knowledge','language','laugh',
	'learning','leather','letter','level','light','limit','linen','liquid',
	'machine','manager','market','measure','meeting','memory','metal','middle',
	'minute','money','month','morning','mother','motion','mountain','music',
	'nation','night','noise','number','observation','offer','operation',
	'opinion','order','organisation','ornament','owner','paint','paper','paste',
	'payment','peace','person','place','plant','pleasure','point','poison',
	'polish','porter','position','powder','power','price','print','process',
	'produce','profit','property','prose','protest','punishment','purpose',
	'quality','question','range','reaction','reading','reason','record',
	'regret','relation','religion','representative','request','respect','reward',
	'rhythm','river','scale','science','secretary','selection','sense','servant',
	'shade','shake','shame','shock','silver','sister','sleep','slope','smash',
	'smell','smile','smoke','sneeze','society','sound','space','stage','start',
	'statement','steam','steel','stitch','stone','story','stretch','structure',
	'substance','sugar','suggestion','summer','support','surprise','system',
	'taste','teaching','tendency','theory','thing','thought','thunder','touch',
	'trade','transport','trick','trouble','twist','value','verse','vessel',
	'voice','waste','water','weather','weight','winter','woman','wound','writing'
];

module.exports = wordList;

